# Spring配置
spring:
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: i18n/messages
  profiles:
    active: '@profileActive@'
  thymeleaf:
    prefix: classpath:/templates/ # 不加，使用默认配置也行
    suffix: .html # 不加，使用默认配置也行
    content-type: text/html
    encoding: UTF-8
    cache: false # 开发环境关闭缓存
    mode: LEGACYHTML5 # 执行thymeleaf非严格html模式

# MyBatis配置
mybatis:
  # 搜索指定包别名
  typeAliasesPackage: com.example.**.pojo
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath*:mapper/*Mapper.xml
  # 加载全局的配置文件
#  configLocation: classpath:mybatis/mybatis-config.xml